runtime: python311
entrypoint: gunicorn -b :$8000 vehiculos_rest.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "vehiculos_rest/vehiculos_rest/settings"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_pending_latency: 30ms

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
